[package]
name = "rpc_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
prettyplease = "0.2.37"
proc-macro2 = "1.0.101"
quote = "1.0.41"
syn = { version = "2.0.106", features = ["extra-traits", "full", "parsing"] }
